<p><u><font size="5"><b>Полулюкс А улучшенный</b>:</font></u></p><p class="MsoNormal" style="text-align: justify;"><font face="Times New Roman, serif"><span style="font-size: 19px;">Отель "ТуСтань" предлагает высокий уровень современного комфорта на&nbsp;<strong>отдыхе в Сходнице</strong>. Отель приглашает&nbsp;тех, кто привык к наилучшему и способен оценить истинный вкус и стиль.</span></font></p><p align="LEFT">Полулюкс А улучшенный - это двухместный однокомнатный номер площадью 24 м.кв.</p><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;"><p align="LEFT" lang="zxx">В номере:</p></blockquote><p align="LEFT" lang="zxx"></p><ul><li>двуспальная кровать,</li><li>паркетное покрытие,</li><li>мягкий уголок,</li><li>настольная лампа, торшер,</li><li>спутниковое ТВ, плазменный телевизор,</li><li>Wi-Fi,</li><li>холодильник,</li><li>сейф,</li><li>кондиционер,</li><li>электрический чайник,</li><li>телефоны (1 в номере, 1 в санузле),</li><li>тумба для багажа,</li><li>шкаф-купе,</li><li>балкон,</li><li>санузел площадью 6 кв.м: душевая кабина, умывальник, зеркало, биде, унитаз, сушилка для волос, пол с подогревом, полотенцесушитель, косметический набор, одноразовые тапочки, халаты,</li><li>3 полотенца на человека,</li><li>фен, весы</li><li>балкон.</li></ul>

<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span style="background-color: rgb(240, 247, 160);">Цены на проживание в&nbsp;отельном комплексе&nbsp;«ТуСтань» с&nbsp;лечебно-оздоровительной базой</span></u></b></p>
<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span lang="UK">ПОЛУЛЮКС А УЛУЧШЕННЫЙ</span></u></b></p>
<table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(0, 32, 96);">Обычный сезон</span></u></b></td>
<td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">15.01.15 - 30.06.15<br>
01.09.15р - 24.12.15</span></b></td></tr>
<tr><td align="center" width="132">
<b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Турис­тический сбор</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1 чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">919</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">989</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">7,79</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="color: rgb(0, 32, 96); font-family: Arial, monospace; font-size: 15px; text-indent: 20px; background-color: rgb(240, 247, 160);">1059</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">1199</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">7,79</span></td></tr>
<tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(192, 0, 0);">Высокий сезон</span></u></b></td><td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">01.07.15 - 31.08.15<br>25.12.15 - 15.01.16</span></b></td></tr>
<tr><td align="center" width="132"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Турис­тический сбор</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1020</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1090</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">8,80</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1160</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1300</span></td>
<td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">8,80</span></td></tr>
</tbody></table>
<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 10.5pt;">*В каждом номере есть возможность размещения на дополнительном месте</span></b></p><table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td align="center" width="162">Дополнительное место для взрослого</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">280</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">350</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,40</span></td></tr><tr><td align="center" width="162">Дополнительное место детское (дети до 12 лет)</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">250</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">300</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,30</span></td></tr></tbody></table>

<br><div style="text-align: center;"><b>ФОТО НОМЕРА</b></div>
<div style="text-align: center;"><img src="/images/upload/2014_06_20/47/354ee31bba2aa688f5f2690f2a091076327039_23_22.gif" alt="" class="uploaded_img" id="upload_images996" onclick="parent.edit_img('upload_images996')" align="right" height="233" hspace="2" vspace="2" width="350"><img src="/images/upload/2014_06_20/16/fd23d4e28b32dfc72b9dc744d22d9ef4977039_03_22.gif" alt="" class="uploaded_img" id="upload_images3522" onclick="parent.edit_img('upload_images3522')" align="left" height="233" hspace="2" vspace="2" width="350"></div>