<p><u><font size="5"><b>Полулюкс А</b>:</font></u></p>
<p class="MsoNormal" style="text-align: justify;"><font face="Times New Roman, serif"><span style="font-size: 19px;">Отель "ТуСтань" предлагает высокий уровень современного комфорта на <strong>отдыхе в Сходнице</strong>. Отель приглашает&nbsp;тех, кто привык к наилучшему и способен оценить истинный вкус и стиль.</span></font></p>
<p align="LEFT">Полулюкс А - это двухместный однокомнатный номер площадью 23 м.кв.</p><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;">
<p align="LEFT" lang="zxx">В номере:</p></blockquote><p align="LEFT" lang="zxx"></p><ul><li>двуспальная кровать,</li><li>паркетное покрытие,</li><li>мягкий уголок,</li><li>настольная лампа, торшер,</li><li>спутниковое ТВ, плазменный телевизор,</li><li>Wi-Fi,</li><li>холодильник,</li><li>сейф,</li><li>кондиционер,</li><li>электрический чайник,</li><li>телефоны (1 в номере, 1 в санузле),</li><li>тумба для багажа,</li><li>шкаф-купе,</li><li>балкон,</li><li>санузел площадью 6 кв.м: душевая кабина, умывальник, зеркало, биде, унитаз, сушилка для волос, пол с подогревом, полотенцесушитель, косметический набор, одноразовые тапочки, халаты,</li><li>3 полотенца на человека,</li><li>фен, весы.</li></ul>
<p class="MsoNormal" align="center"><b><u>Цены на проживание в<span style="background-color: rgb(240, 247, 160);">&nbsp;отельном комплексе&nbsp;«ТуСтань» с&nbsp;лечебно-оздоровительной базой</span></u></b></p><p align="center"><b><u><span lang="UK"><font size="4">Полулюкс А</font></span></u></b></p>

<table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(0, 32, 96);">Обычный сезон</span></u></b></td>
<td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">15.01.15 - 30.06.15<br>
01.09.15р - 24.12.15</span></b></td></tr>
<tr><td align="center" width="132">
<b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Турис­тический сбор</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1 чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">868</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">938</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">7,28</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="color: rgb(0, 32, 96); font-family: Arial, monospace; font-size: 15px; text-indent: 20px; background-color: rgb(240, 247, 160);">1008</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">1148</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">7,28</span></td></tr>
<tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(192, 0, 0);">Высокий сезон</span></u></b></td><td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">01.07.15 - 31.08.15<br>25.12.15 - 15.01.16</span></b></td></tr>
<tr><td align="center" width="132"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Турис­тический сбор</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">935</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1005</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">7,95</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1075</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1215</span></td>
<td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">7,95</span></td></tr>
</tbody></table>
<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 10.5pt;">*В каждом номере есть возможность размещения на дополнительном месте</span></b></p><table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td align="center" width="162">Дополнительное место для взрослого</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">280</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">350</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,40</span></td></tr><tr><td align="center" width="162">Дополнительное место детское (дети до 12 лет)</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">250</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">300</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,30</span></td></tr></tbody></table>
<b><div style="text-align: center;"><b><font size="5"><br></font></b></div><div style="text-align: center;"><b><font size="5">Фото номера</font></b></div></b><div style="text-align: center;"><img src="http://hoteltustan.com.ua/images/upload/2014_06_20/38/04735372ee33e9727694daaa7d1719fc960906_25_00.gif" alt="полулюкс А Тустань Сходница" class="uploaded_img" id="upload_images487" align="middle" hspace="5px" vspace="5px" width="400px"></div>