<p><u><font size="5"><b>Стандарт</b></font></u></p>
<p class="MsoNormal" style="text-align: justify;"><font face="Times New Roman, serif"><span style="font-size: 19px;">Отель "ТуСтань"&nbsp;обеспечивает высокий уровень современного комфорта. Мы приглашаем на <strong>отдых в Сходницу</strong> тех, кто привык к самому лучшему, кто способен оценить истинный вкус и изысканный стиль.</span></font></p><p align="LEFT" lang="zxx">Стандарт - это двухместный однокомнатный номер площадью 20 м.кв.</p><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;"><p align="LEFT" lang="zxx">В номере:</p></blockquote><p align="LEFT" lang="zxx"></p><ul><li>двуспальная кровать или две полуторные кровати,</li><li>паркетное покрытие,</li><li>мягкий уголок,</li><li>настольная лампа, торшер,</li><li>спутниковое ТВ, плазменный телевизор,</li><li>Wi-Fi,</li><li>холодильник,</li><li>сейф,</li><li>кондиционер,</li><li>телефоны (1 в номере, 1 в санузле),</li><li>шкаф-купе,</li><li>санузел площадью 6 кв.м: душевая кабина, умывальник, зеркало, биде, унитаз, сушилка для волос, пол с подогревом, полотенцесушитель, косметический набор, одноразовые тапочки, халаты,&nbsp;</li><li>3 полотенца на человека,&nbsp;</li><li>фен, весы.</li></ul>
<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span style="background-color: rgb(240, 247, 160);">Цены на проживание в&nbsp;отельном комплексе&nbsp;«ТуСтань» с&nbsp;лечебно-оздоровительной базой</span></u></b></p>
<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span lang="UK">Стандарт А та Стандарт В</span></u></b></p>
<table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(0, 32, 96);">Обычный сезон</span></u></b></td>
<td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">15.01.15 - 30.06.15<br>
01.09.15р - 25.12.15</span></b></td></tr>
<tr><td align="center" width="132">
<b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Турис­тический сбор</span></b></td></tr>
<tr style="page-break-inside: avoid; height: 11.65pt;"><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Стандарт В</span></b></td></tr><tr><td align="center" width="162"><span style="font-size: 11pt;">1 чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">580</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">650</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">4,40</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">720</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">860</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">4,40</span></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Стандарт А</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">670</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">740</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">5,30</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td><td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">810</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">950</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">5,30</span></td></tr><tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(192, 0, 0);">Высокий сезон</span></u></b></td><td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">01.07.15 - 31.08.15<br>25.12.15 - 15.01.16</span></b></td></tr>
<tr><td align="center" width="132"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Турис­тический сбор</span></b></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt;">Стандарт В</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">672</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">742</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">5,32</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">812</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">952</span></td>
<td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">5,32</span></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt;">Стандарт А</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">750</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">820</span></td>
<td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">6,10</span></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">2&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">890</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">1030</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">6,10</span></td></tr></tbody></table>
<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 10.5pt;">*В каждом номере есть возможность размещения на дополнительном месте</span></b></p><table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td align="center" width="162">Дополнительное место для взрослого</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">280</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">350</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,40</span></td></tr><tr><td align="center" width="162">Дополнительное место детское (дети до 12 лет)</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">250</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">300</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,30</span></td></tr></tbody></table>

<p style="text-align: center;"><b><font size="5">Фото номеров</font></b></p><p style="margin-bottom: 0cm;" align="left"><font size="3"><b><img src="/images/upload/2015_02_10/37/e8bc57d83a5d0c3e0f367fbd38dd544c805534_42_21.gif" width="350px" alt="" vspace="0px" hspace="0px" class="uploaded_img" id="upload_images1066" align="left" onclick="parent.edit_img('upload_images1066')">
<img src="/images/upload/2015_02_10/10/c590668dd8c42dacfec2729df7aa1049761837_00_21.gif" width="350px" alt="" vspace="0px" hspace="0px" class="uploaded_img" id="upload_images4570" align="right" onclick="parent.edit_img('upload_images4570')"></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><br></b></font></p><p style="margin-bottom: 0cm;" align="CENTER"><font size="3"><b><font size="5">Стандарт Б &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;Стандарт А</font></b></font></p><img src="http://hoteltustan.com.ua/images/upload/2014_06_20/33/52bad50a277cc4402024fb8db9cf3017437909_25_22.gif" alt="" class="uploaded_img" id="upload_images6764" align="right" height="233" hspace="2" vspace="2" width="350"><img src="http://hoteltustan.com.ua/images/upload/2014_06_20/43/a08e395b97422b0cc54dfadd91e4a85c429607_41_22.gif" alt="" class="uploaded_img" id="upload_images1639" align="left" height="233" hspace="2" vspace="2" width="350"><div><br></div>