<p><font size="4">Именно для Вас <b>отель лечебно-оздоровительный комплекс "Тустань"</b> предлагаем ряд лечебно-оздоровительных <b><u>процедур</u></b>:

</font></p><p style="text-align: center;"><img src="/images/upload/2014_06_14/17/efbd689300c7b563e0e4cc50c716579e926348_59_20.gif" width="200px" alt="минеральные ванны отель тустань" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images4622" align="left" onclick="parent.edit_img('upload_images4622')"></p><p style="text-align: center;"> <font size="4"><u><b>ВОДОЛЕЧЕНИЕ</b></u></font></p><p>
</p><li><font face="Verdana, Geneva, sans-serif"><b>душ Шарко;</b></font></li>
<li><font face="Verdana, Geneva, sans-serif"><b>циркулярный душ;</b></font></li>
<li><font face="Verdana, Geneva, sans-serif"><b>подводный душ-массаж</b> с озонированием и хронотерапией;</font></li>

<li><font face="Verdana, Geneva, sans-serif">ванны:</font></li>
<p><font face="Verdana, Geneva, sans-serif"> - <u>жемчужная;</u></font></p><p>
</p><p><font face="Verdana, Geneva, sans-serif"> -  <u>хвойная;</u></font></p><p>
</p><p><font face="Verdana, Geneva, sans-serif"> - <u>валериановая;</u></font></p><p>
</p><p><font face="Verdana, Geneva, sans-serif"> - <u>ванна  «Клеопатры»;</u></font></p><p>
</p><p><font face="Verdana, Geneva, sans-serif"> - <u>"винные" ванны.</u></font></p><p style="text-align: center;"><font size="4"><u><b>СПЕЛЕОТЕРАПИЯ</b></u>&nbsp;(соляная комната)</font></p><p><img src="http://hoteltustan.com.ua/images/upload/2014_06_14/14/7052b55685a7dd98bdcc1a07427252b3244146_32_20.gif" height="200px" alt="отель Тустань спелеотерапия" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images9151" align="right"></p><p style="text-align: justify;"><font face="Verdana, Geneva, sans-serif"><b>Соляная комната в Сходнице</b>&nbsp;всецело обработана
природной каменной солью с курортов Артемовска и Солотвино. В основе метода
спелеотерапии лежит пребывание пациента в аэрозольной среде<span lang="EN-US">&nbsp;</span>насыщенной<span lang="EN-US">&nbsp;</span>соляным аэрозолем<span lang="EN-US">&nbsp;</span>с предельной концентрацией.&nbsp;&nbsp;Соляные гроты имеют лечебные свойства, по:</font></p><p></p><li><font face="Verdana, Geneva, sans-serif">заболеванию органов дыхания;</font></li><li><font face="Verdana, Geneva, sans-serif">аллергические и кожаные заболевания;</font></li><li><font face="Verdana, Geneva, sans-serif">неврозы и состояние переутомления;</font></li><p><font face="Verdana, Geneva, sans-serif"></font></p><p></p><p></p><li style="color: rgb(0, 0, 0); font-style: normal; font-variant: normal; font-weight: normal; letter-spacing: normal; line-height: normal; orphans: auto; text-indent: 0px; text-transform: none; white-space: normal; widows: auto; word-spacing: 0px; -webkit-text-stroke-width: 0px;"><font face="Verdana, Geneva, sans-serif">сердечно-сосудистые заболевания.</font></li><p style="text-align: center;"><u style="font-size: large;"><b>ФИЗИОТЕРАПЕВТИЧЕСКИЕ ПРОЦЕДУРЫ</b></u></p><p>
</p><li><span style="font-family: Verdana, Geneva, sans-serif;">Сухая углекислая ванна;</span></li><li><span style="font-family: Verdana, Geneva, sans-serif;">магнитотерапия;</span></li><li><font face="Verdana, Geneva, sans-serif">ультразвуковая терапия;</font></li><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">УВЧ;</font></li><font face="Verdana, Geneva, sans-serif"> 
</font><li><span style="font-family: Verdana, Geneva, sans-serif;">дарсонвализация;</span></li><font face="Verdana, Geneva, sans-serif">
</font><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">прессотерапия;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">тубус-кварц;</span></li><font face="Verdana, Geneva, sans-serif">
</font><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">электротерапия.</font></li><p></p><p><img src="/images/upload/2014_06_14/18/985deff75ab0265c43947eee53a6b35b198852_12_20.gif" height="200px" alt="физпроцедуры Тустань" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images1755" align="middle" onclick="parent.edit_img('upload_images1755')"><img src="/images/upload/2014_06_14/23/5b0ab80598595d15659db8faba0a133d290652_48_20.gif" height="200px" alt="физпроцедуры Тустань Сходница" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images8336" align="middle" onclick="parent.edit_img('upload_images8336')"></p><p><span style="font-family: Verdana, Geneva, sans-serif;">Все процедуры в отеле Тустань проводят на аппаратах  ведущих фирм Европы.</span></p><p>
</p><p><font size="4"><u><br></u></font></p><p style="text-align: center;"><font size="4"><u><b>ЭЛЕКТРОКАРДИОГРАФИЯ</b></u></font></p><p><img src="/images/upload/2014_06_14/21/cf6e93a31a7940162374880b2eb45d66276553_44_20.gif" height="200px" alt="физпроцедуры отель Тустань" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images3782" align="middle" onclick="parent.edit_img('upload_images3782')"></p><p>
</p><p style="text-align: center;"><font size="4"><u><b>ОЗОКЕРИТОТЕРАПИЯ</b></u></font></p><p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph"><b><span style="font-family: Verdana, sans-serif;">Озокеритотерапия</span></b><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;<span style="font-family: Verdana, sans-serif;">- самый популярный в</span><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;</span></span><b><u><span style="font-family: Verdana, sans-serif;">Карпатах</span></u></b><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;<span style="font-family: Verdana, sans-serif;">вид теплолечения, где в качестве термического
агента применяют преднамеренно обработанный натуральный минерал нефтевого
происхождения - озокерит. Такое лечение теплом содействует улучшению циркуляции
крови, формирования биологических веществ, и также выявляет глубокое
прогревание организма, болеуспокаительное и антибактериальное действие. Также
оно поддерживает пациентов с повреждениями связок, мышц и суставов, заболеваниями
кожи, заболеваниями нервной системы и спинного мозга, а также заболеваниями
внутренних органов.</span></span><o:p></o:p></p><p style="text-align: center;"><u style="font-size: large;"><b>ИНГАЛЯЦИОННАЯ ТЕРАПИЯ</b></u><span style="font-size: large;"> с  использованием:</span></p><p>
</p><li><span style="font-family: Verdana, Geneva, sans-serif;">морской соли;</span></li><li><font face="Verdana, Geneva, sans-serif">эфирных масел;</font></li><font face="Verdana, Geneva, sans-serif">
</font><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">медицинских препаратов.</font></li><font size="4">
</font><p style="text-align: center;"><font size="4"><u><b>КОСМЕТИЧЕСКИЕ УСЛУГИ</b></u></font></p><p><font size="4"><u><b>ДЛЯ ЛИЦА</b>:</u></font></p><img src="/images/upload/2014_06_14/12/a61f48f3cdf367f6e3878e8760b02b6e133803_39_21.gif" height="200px" alt="косметология отель Тустань Сходница" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images2275" align="right" onclick="parent.edit_img('upload_images2275')"><p></p><li><font face="Verdana, Geneva, sans-serif">программы увлажнения и питания кожи;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">ручная чистка-пилинг;</span></li><li><font face="Verdana, Geneva, sans-serif">лечение проблемной кожи;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">разные виды массажа</span><font face="Verdana, Geneva, sans-serif">;</font></li><li><font face="Verdana, Geneva, sans-serif">аппаратная кислородная безинекционная мезотерапия;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">лифтинг терапия</span><font face="Verdana, Geneva, sans-serif">.</font></li><p><font size="4"><u><b>ДЛЯ ТЕЛА:</b></u></font></p><p></p><li><span style="font-family: Verdana, Geneva, sans-serif;">Антицеллюлитные программы;</span></li><li><font face="Verdana, Geneva, sans-serif">Лимфодренажный «бамбуковый» массаж;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">Обертывание (шоколадное, минеральное)</span><font face="Verdana, Geneva, sans-serif">.</font></li><p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph"><span style="font-family: Verdana, sans-serif;">Все
косметические процедуры проводят с применением профессиональной косметики с Италии GERARD'S. В гостей отеля есть возможность приобрести пакетные программы по
омолаживанию организма.</span><o:p></o:p></p><p></p><p style="text-align: center;"><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><font size="4" style="text-align: start;"></font><img src="http://hoteltustan.com.ua/images/news/small_technical_day.jpg" width="47%" style="text-align: start;"><span style="text-align: start;">&nbsp;</span><img src="http://hoteltustan.com.ua/images/news/small_kerala1.jpg" width="35%" style="text-align: start;"><span style="text-align: start;"></span></p><p class="MsoNormal" style="text-align:justify;text-justify:inter-ideograph"><span style="font-family: Verdana, sans-serif;">Эти
процедуры помогают</span><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;</span><span style="font-family: Verdana, sans-serif;">сохранить молодость и красоту, прибавят заряд
энергии и бодрости, способствуют выведению токсинов, стимулируют уменьшение</span><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;</span><span style="font-family: Verdana, sans-serif;">веса
и восстановят</span><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;</span><span style="font-family: Verdana, sans-serif;">минеральный</span><span lang="EN-US" style="font-family: Verdana, sans-serif;">&nbsp;</span><span style="font-family: Verdana, sans-serif;">баланс
кожи.</span><o:p></o:p></p><p style="text-align: center;"><font size="4"><u><b>МАССАЖНЫЕ УСЛУГИ</b></u></font></p><p></p><li><font face="Verdana, Geneva, sans-serif">Лечебный массаж;</font></li><p style="text-align: center;"><font style="text-align: start;" face="Verdana, Geneva, sans-serif"></font></p><li><font face="Verdana, Geneva, sans-serif">Антицеллюлитный массаж;</font></li><p style="text-align: center;"><font size="4"><b><u>ГИРУДОТЕРАПИЯ</u> </b>(использование медицинских пиявок)</font></p><p><img src="/images/upload/2014_06_14/40/36796104c75936cd75d4f873b70b760e862905_02_21.gif" height="200px" alt="отель Тустань" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images2055" align="middle" onclick="parent.edit_img('upload_images2055')"><img src="/images/upload/2014_06_14/24/37b45da8e6a1393c17dca5e015b90d3d261505_31_21.gif" height="200px" alt="отель Тустань" vspace="5px" hspace="5px" class="uploaded_img" id="upload_images2148" align="middle" onclick="parent.edit_img('upload_images2148')"></p><p style="text-align: center;"><font size="4"><b><u>АПИТЕРАПИЯ</u> </b>(медицинское использование  пчелиного яда)</font></p><p style="text-align: justify;"><font face="Verdana, Geneva, sans-serif">В отеле "Тустань" широко используют метод лечения с использованием пчелиного яда и продуктов пчеловодства  для оздоровления организма.</font></p><p style="text-align: justify;"><font face="Verdana, Geneva, sans-serif">Консультирует невропатолог&nbsp;Сенишын Д.М., врач народной медицины, почетный апитерапевт Украины.&nbsp;</font></p><p style="text-align: center;">
<img src="/images/news/small_images67.jpg" width="40%"> 
<img src="/images/news/small_images68.jpg" width="46%"> 
</p><p style="text-align: center;"><u style="font-size: large;"><b>ПРЕДОСТАВЛЯЮТСЯ  ПЛАТНЫЕ   КОНСУЛЬТАЦИИ  ТАКИХ  ВРАЧЕЙ:</b></u></p><p>
</p><li><span style="font-family: Verdana, Geneva, sans-serif;">Гинеколога;</span></li><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">Диетолога;</font></li><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">Педиатра;</font></li><li><span style="font-family: Verdana, Geneva, sans-serif;">Эндокринолога;</span></li><li><span style="font-family: Verdana, Geneva, sans-serif;">Оториноларинголога;</span></li><font face="Verdana, Geneva, sans-serif">
</font><font face="Verdana, Geneva, sans-serif">
</font><font face="Verdana, Geneva, sans-serif">
</font><li><font face="Verdana, Geneva, sans-serif">Кардиолога;</font></li><font size="4">
</font><p>



</p><p><font size="4">На базе отеля Тустань функционирует лабораторный центр « MeDiS” с манипуляционным кабинетом по забору крови.</font></p>

