<p><u><font size="5"><b>Одноместный</b></font></u></p>
<p class="MsoNormal" style="text-align: justify;"><font face="Times New Roman, serif"><span style="font-size: 19px;">Отель "ТуСтань"&nbsp;обеспечивает высокий уровень современного комфорта. Мы приглашаем на <strong>отдых в Сходницу</strong> тех, кто привык к самому лучшему, кто способен оценить истинный вкус и изысканный стиль.</span></font></p><p align="LEFT" lang="zxx">Одноместный - это однокомнатный номер площадью 8,5 м.кв.</p><blockquote style="margin: 0px 0px 0px 40px; border: none; padding: 0px;"><p align="LEFT" lang="zxx">В номере:</p></blockquote><p align="LEFT" lang="zxx"></p><ul><li>полуторная кровать,</li><li>ковровое покрытие или паркетное<br></li><li>настольная лампа, торшер,</li><li>спутниковое ТВ, плазменный телевизор,</li><li>Wi-Fi,</li><li>холодильник,</li><li>сейф,</li><li>телефоны (1 в номере, 1 в санузле),</li><li>шкаф-купе,</li><li>санузел площадью 4,5 кв.м: душевая кабина, умывальник, зеркало, биде, унитаз, сушилка для волос, пол с подогревом, полотенцесушитель, косметический набор, одноразовые тапочки, халаты,&nbsp;</li><li>3 полотенца на человека,&nbsp;</li><li>фен, весы.</li></ul>
<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span style="background-color: rgb(240, 247, 160);">Цены на проживание в&nbsp;отельном комплексе&nbsp;«ТуСтань» с&nbsp;лечебно-оздоровительной базой</span></u></b></p>
<p class="MsoNormal" style="text-align: center;" align="center"><b><u><span lang="UK">Одноместный А и Одноместный В</span></u></b></p>
<table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(0, 32, 96);">Обычный сезон</span></u></b></td>
<td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">15.01.15 - 30.06.15<br>
01.09.15р - 25.12.15</span></b></td></tr>
<tr><td align="center" width="132">
<b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Турис­тический сбор</span></b></td></tr>
<tr style="page-break-inside: avoid; height: 11.65pt;"><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Одноместный В</span></b></td></tr><tr><td align="center" width="162"><span style="font-size: 11pt;">1 чел. в номере</span></td>
<td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">470</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">540</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">3,30</span></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt; color: rgb(0, 32, 96);">Одноместный А</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" valign="top" width="132"><span style="font-size: 11pt; color: rgb(0, 32, 96);">620</span></td>
<td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">690</span></td><td align="center" valign="top" width="142"><span style="font-size: 11pt; color: rgb(0, 32, 96);">4,80</span></td></tr>
<tr><td rowspan="2" align="center" width="162"><b><u><span style="font-size: 11pt; color: rgb(192, 0, 0);">Высокий сезон</span></u></b></td><td colspan="3" align="center" width="416"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">01.07.15 - 31.08.15<br>25.12.15 - 15.01.16</span></b></td></tr>
<tr><td align="center" width="132"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + завтраки</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Прожи­вание + полный пансион</span></b></td><td align="center" width="142"><b><span style="font-size: 11pt; color: rgb(192, 0, 0);">Турис­тический сбор</span></b></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt;">Стандарт В</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">507</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">577</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">3,67</span></td></tr>
<tr><td colspan="4" align="center" width="577"><b><span style="font-size: 11pt;">Стандарт А</span></b></td></tr>
<tr><td align="center" width="162"><span style="font-size: 11pt;">1&nbsp;чел. в номере</span></td><td align="center" width="132"><span style="font-size: 11pt; color: rgb(192, 0, 0);">668</span></td><td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">738</span></td>
<td align="center" width="142"><span style="font-size: 11pt; color: rgb(192, 0, 0);">5,28</span></td></tr>
</tbody></table>
<p class="MsoNormal" style="text-align: center;" align="center"><b><span style="font-size: 10.5pt;">*В каждом номере есть возможность размещения на дополнительном месте</span></b></p><table class="MsoNormalTable" align="center" border="1" cellpadding="0" cellspacing="0" width="577"><tbody><tr><td align="center" width="162">Дополнительное место для взрослого</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">280</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">350</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,40</span></td></tr><tr><td align="center" width="162">Дополнительное место детское (дети до 12 лет)</td><td align="center" width="132"><span style="color: rgb(0, 32, 96);">250</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">300</span></td><td align="center" width="142"><span style="color: rgb(0, 32, 96);">1,30</span></td></tr></tbody></table>

<div style="text-align: center;"><b><font size="4">Фото номера</font></b></div><div style="text-align: center;"><b><font size="4">Одноместный В</font></b></div><div style="text-align: center;"><img src="/images/upload/2014_06_21/44/b9986f0104d08e793733d79ff4703cff924406_56_10.gif" alt="одноместный отель Тустань" class="uploaded_img" id="upload_images4161" onclick="parent.edit_img('upload_images4161')" align="left" height="233px" hspace="2px" vspace="2px" width="350px"></div><div style="text-align: center;"><img src="/images/upload/2014_06_21/32/5cf8e3984471406876eb69119076b88b683907_43_10.gif" alt="одноместный отель Тустань" class="uploaded_img" id="upload_images2296" onclick="parent.edit_img('upload_images2296')" align="right" height="233px" hspace="2px" vspace="2px" width="350px"></div><div style="text-align: center;"><b><font size="4">Одноместный А</font></b></div><p align="LEFT" lang="zxx"><img src="/images/upload/2014_06_21/53/0e03480b0b5189eeabab53f5540d03e2934408_36_10.gif" alt="одноместный отель Тустань" class="uploaded_img" id="upload_images4149" onclick="parent.edit_img('upload_images4149')" align="left" height="233px" hspace="2px" vspace="2px" width="350px"><img src="/images/upload/2014_06_21/23/d88a5221d08445ede2360384bba96e6f497910_00_10.gif" alt="одноместный отель Тустань" class="uploaded_img" id="upload_images728" onclick="parent.edit_img('upload_images728')" align="right" height="233px" hspace="2px" vspace="2px" width="350px">
</p>